.l# -*- coding: utf-8 -*-
"""Length-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r6SCnxwcyRVfIRpiCnQroydZiP2U1Iob
"""

pip install pyspark

import re
from pyspark import SparkConf, SparkContext

conf  = SparkConf().setMaster("local[*]").setAppName("length") 
sc = SparkContext(conf=conf)

text = sc.textFile("Amazon_Comments.csv")
text_1 = text.map(lambda x: x.split("^"))

#clean text from comments ''
text_clean = text_1.map(lambda x: (x[0], x[6], len(re.sub('\W+', ' ', x[5]).strip().split(" "))))

#calculate total length and count of comments for each rating.
rating_lengths = text_clean.map(lambda x: (x[0], (x[2], 1))) \
    .reduceByKey(lambda x, y: (x[0]+y[0], x[1]+y[1]))

#calculate average length for each rating
avg_lengths = rating_lengths.mapValues(lambda x: x[0]/x[1])

#results
for rating, avg_length in avg_lengths.collect():
    print(f"Rating {rating}: Average comment length = {avg_length:.2f}")